#!/bin/bash
# ============================================================================
# fix_stereo_udev.sh  —  Run ONCE on the miniPC to give the stereo camera
# a stable /dev/video_stereo symlink regardless of which USB port it's in.
#
# Why the port changes:
#   Linux V4L2 enumerates USB video devices in the order they enumerate on
#   boot or plug-in. If the stereo camera and another device (e.g. a USB hub)
#   both appear at startup, their /dev/videoN numbers race. A udev rule pins
#   the symlink by the camera's USB Vendor ID and Product ID instead.
#
# Usage:
#   bash fix_stereo_udev.sh          # installs the udev rule
#   bash fix_stereo_udev.sh detect   # just prints camera info, no install
# ============================================================================

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; RED='\033[0;31m'; NC='\033[0m'
ok()   { echo -e "  ${GREEN}✓${NC} $1"; }
warn() { echo -e "  ${YELLOW}⚠${NC} $1"; }
err()  { echo -e "  ${RED}✗${NC} $1"; }
log()  { echo -e "${CYAN}[udev]${NC} $1"; }

echo ""
log "Detecting USB video devices..."
echo ""

# ── Find all V4L2 devices and their USB IDs ───────────────────────────────────
STEREO_DEV=""
STEREO_VENDOR=""
STEREO_PRODUCT=""

for dev in /dev/video*; do
    [ -e "$dev" ] || continue

    # Get device info from udevadm
    INFO=$(udevadm info --query=all --name="$dev" 2>/dev/null)

    VENDOR=$(echo "$INFO"  | grep "ID_VENDOR_ID="  | cut -d= -f2)
    PRODUCT=$(echo "$INFO" | grep "ID_MODEL_ID="   | cut -d= -f2)
    NAME=$(echo "$INFO"    | grep "ID_MODEL="      | cut -d= -f2 | head -1)
    BUS=$(echo "$INFO"     | grep "ID_PATH="       | cut -d= -f2)

    # Skip RealSense
    if echo "$INFO" | grep -qi "RealSense\|Intel"; then
        echo "  $dev  [RealSense / Intel — skipping]"
        continue
    fi

    echo "  $dev  vendor=$VENDOR  product=$PRODUCT  name='$NAME'  bus=$BUS"

    # Pick the first non-RealSense device as stereo candidate
    if [ -z "$STEREO_DEV" ] && [ -n "$VENDOR" ]; then
        STEREO_DEV="$dev"
        STEREO_VENDOR="$VENDOR"
        STEREO_PRODUCT="$PRODUCT"
        STEREO_NAME="$NAME"
        STEREO_BUS="$BUS"
    fi
done

echo ""

if [ "$1" = "detect" ]; then
    if [ -n "$STEREO_DEV" ]; then
        ok "Stereo camera candidate: $STEREO_DEV"
        echo "    Vendor:  $STEREO_VENDOR"
        echo "    Product: $STEREO_PRODUCT"
        echo "    Name:    $STEREO_NAME"
    else
        warn "No non-RealSense USB video device found."
        warn "Make sure the stereo camera is plugged in."
    fi
    exit 0
fi

if [ -z "$STEREO_DEV" ]; then
    err "No stereo camera detected. Plug it in and re-run."
    exit 1
fi

ok "Stereo camera: $STEREO_DEV  (vendor=$STEREO_VENDOR product=$STEREO_PRODUCT)"
echo ""
log "Installing udev rule..."

RULE_FILE="/etc/udev/rules.d/99-stereo-camera.rules"

sudo tee "$RULE_FILE" > /dev/null << RULE
# Lunar Rover — stereo USB camera stable symlink
# Generated by fix_stereo_udev.sh  (vendor=$STEREO_VENDOR product=$STEREO_PRODUCT)
# The symlink /dev/video_stereo will always point to this camera regardless
# of which /dev/videoN it gets assigned at boot.
SUBSYSTEM=="video4linux", ATTRS{idVendor}=="$STEREO_VENDOR", ATTRS{idProduct}=="$STEREO_PRODUCT", SYMLINK+="video_stereo"
RULE

if [ $? -eq 0 ]; then
    ok "Rule written to $RULE_FILE"
else
    err "Failed to write udev rule (need sudo?)"
    exit 1
fi

# Reload udev rules
sudo udevadm control --reload-rules
sudo udevadm trigger
sleep 1

if [ -e /dev/video_stereo ]; then
    ok "/dev/video_stereo symlink created → $(readlink /dev/video_stereo)"
else
    warn "/dev/video_stereo not created yet — unplug and replug the stereo camera"
    warn "Then verify: ls -la /dev/video_stereo"
fi

echo ""
echo "  Done! From now on the stereo camera is always at /dev/video_stereo"
echo "  The full_launch_minipc.sh script will use this automatically."
echo ""
echo "  Verify after replugging:"
echo "    ls -la /dev/video_stereo"
echo "    v4l2-ctl --device /dev/video_stereo --info"